import {ModelLimits,defaultLimits} from "./model-limits.jsx";
import {HealthPanel} from "./health-panel.jsx";
import {ModelRoleFields,rolePool} from "./model-setup.jsx";
import { useEffect, useState } from "react";
import {jobMessage,jobStatistics} from "./job-message.js";

const title=item=>item?.ownerLabel||item?.ownerTitle||item?.label||item?.title||item?.id;
const verificationLabels={"source-checked":"Описание сверено с кодом",verified:"Описание подтверждено источниками","structure-only":"Структура исходников; назначение ещё не проверено","needs-review":"Нужно повторно сверить",pending:"Проверка идёт","owner-decision":"Уточнение владельца"};
export const statuses={operational:"Реализовано",existing:"Реализовано",planned:"Запланировано",inferred:"Предположение",accepted:"Принято",cancelled:"Отменено",proposed:"Предложено",unresolved:"Нужно уточнить",disabled:"Отключено",active:"В работе",blocked:"Ожидает",completed:"Завершено"};
export function ProjectContext({tab,setTab,snapshot,selection,open,onClose,onRename,onSelect,onRelation,onFlow,api,toast,architect,setArchitect,refresh}) {
  const [flowId,setFlowId]=useState("");const [source,setSource]=useState(null);const [instruction,setInstruction]=useState("");const [action,setAction]=useState("explain");const [otherId,setOtherId]=useState("");const [correction,setCorrection]=useState(null);const [question,setQuestion]=useState("");
  const [limits,setLimits]=useState(defaultLimits);const [observe,setObserve]=useState(false);const [models,setModels]=useState(null);const [provider,setProvider]=useState("codex");const [dialogs,setDialogs]=useState(true);const [roleModels,setRoleModels]=useState({});const [sourceList,setSourceList]=useState(null);
  const map=snapshot.map||{};const historical=Boolean(snapshot._history);const entities=new Map(snapshot.entities.map(item=>[item.id,item]));
  const kind=selection?.kind;const object=kind==="entity"?entities.get(selection.id):kind==="area"?snapshot.areas.find(item=>item.id===selection.id):kind==="route"?(snapshot.relations.find(item=>item.id===(selection.relationId||selection.route?.relationId))||(selection.route?.relations?.length===1?selection.route.relations[0]:{id:selection.route?.id,label:selection.route?.label||"Связи выбранного пути",bundle:true,relations:selection.route?.relations||[]})):kind==="work"?snapshot.work.find(item=>item.id===selection.id):null;
  useEffect(()=>{setSource(null);setInstruction("");},[kind,selection?.id,selection?.relationId]);
  useEffect(()=>{if(architect?.status==="done"&&architect.kind==="correction"&&architect.result?.id)setCorrection({...architect.result,jobStats:jobStatistics(architect)});},[architect]);
  const loadModels=async()=>{try{const response=await api("/api/models");const value=await response.json();if(!response.ok)throw new Error(value.error);setModels(value);setLimits({...defaultLimits,...value.config});setObserve(value.config.enabled===true);setProvider(value.config.modelProvider||"codex");setDialogs(value.config.dialogSources!==false);setRoleModels(value.roles);const sources=await api("/api/sources");if(sources.ok)setSourceList(await sources.json());}catch(error){toast(error.message,true);}};
  useEffect(()=>{if(tab==="settings"&&open)void loadModels();},[tab,open]);
  const post=async(path,body)=>{const response=await api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.error);return value;};
  const run=async(body)=>{try{const value=await post("/api/corrections",body);setArchitect(value);setInstruction("");toast("Поправка обрабатывается. Можно продолжать работу с картой.");}catch(error){toast(error.message,true);}};
  const showSource=async id=>{try{const response=await api(`/api/source?${new URLSearchParams({id,...(snapshot._history?.id?{checkpointId:snapshot._history.id}:{})})}`);const value=await response.json();if(!response.ok)throw new Error(value.error);setSource({...value,selectedRef:id});}catch(error){setSource({selectedRef:id,text:`Источник сейчас недоступен: ${error.message}`});}};
  const sourceUrl=ref=>`/api/source?${new URLSearchParams({id:ref,...(snapshot._history?.id?{checkpointId:snapshot._history.id}:{})})}`;
  const reader=()=>source&&<section className="source-reader"><header><strong>Содержимое источника</strong><button onClick={()=>setSource(null)} aria-label="Закрыть источник">×</button></header><small>{source.path||source.id||source.role}</small><pre>{source.error||source.text||source.content||JSON.stringify(source,null,2)}</pre></section>;
  const evidence=refs=>{const unique=[...new Set((refs||[]).filter(Boolean))];return <section className="evidence-section"><h3>Источники</h3><p className="muted-text">Нажмите на источник — фрагмент откроется ниже. ↗ открывает файл в отдельной вкладке.</p><div className="source-links">{unique.map(ref=><span className="source-link" key={ref}><button onClick={()=>showSource(ref)} aria-expanded={source?.selectedRef===ref}>{ref.startsWith("dialog:")?"Сообщение проекта":ref}</button>{!ref.startsWith("dialog:")&&<a href={`${sourceUrl(ref)}&view=file#L${ref.match(/:(\d+)/)?.[1]||1}`} target="_blank" rel="noopener" title="Открыть файл в отдельной вкладке" aria-label={`Открыть файл ${ref}`}>↗</a>}</span>)}</div>{unique.includes(source?.selectedRef)&&reader()}</section>;};
  useEffect(()=>{if(source)document.querySelector(".context-panel .source-reader>header")?.scrollIntoView({block:"nearest"});},[source]);
  const details=(label,value)=>value&&(Array.isArray(value)?value.length:true)?<div><dt>{label}</dt><dd>{Array.isArray(value)?value.join(" · "):value}</dd></div>:null;
  const copyContext=async()=>{const selected=object?`Выбрано: ${title(object)}\n${object.ownerPurpose||object.purpose||object.ownerNote||object.note||""}\nПолучает: ${(object.inputs||[]).join(", ")}\nПередаёт: ${(object.outputs||[]).join(", ")}\nИсточники: ${[object.path,...(object.evidence||[])].filter(Boolean).join(", ")}`:"";const summary=`${map.projectTitle||"Проект"}\n${map.projectSummary||""}\n${selected}\nСценарии:\n${(map.keyFlows||[]).map(flow=>typeof flow==="string"?flow:`${flow.title}: ${(flow.steps||[]).map(id=>title(entities.get(id))||id).join(" → ")}. ${flow.outcome||""}`).join("\n")}\nРешения:\n${(map.knowledge?.decisions||[]).map(item=>`[${item.status}] ${item.text}`).join("\n")}\nРевизия: ${snapshot.revision}; ${historical?snapshot._history.at:"Live"}`;try{await navigator.clipboard.writeText(summary);toast("Контекст скопирован для нового диалога");}catch{const url=URL.createObjectURL(new Blob([summary],{type:"text/plain;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="project-context.txt";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast("Контекст сохранён в текстовый файл");}};
  const flows=(map.keyFlows||[]).map((flow,index)=>typeof flow==="string"?{id:`legacy-${index}`,title:flow,steps:[],legacy:true}:flow);
  const activeFlow=flows.find(flow=>flow.id===flowId);
  useEffect(()=>{if(!open)setFlowId("");},[open]);
  // Re-entering a scenario restores its path. Background updates never move the camera.
  useEffect(()=>{if(open&&tab==="flows"&&activeFlow&&!activeFlow.legacy)onFlow(activeFlow);},[tab,open,flowId]);
  const pending=architect?.running;
  const jobStats=jobStatistics(architect);
  if(!open)return null;
  return <aside className="context-panel" aria-label="Контекст проекта"><header><strong>{{overview:"О проекте",flows:"Сценарии",decisions:"Решения",settings:"Настройки",health:"Состояние",object:"Детали"}[tab]}</strong><button aria-label="Закрыть контекст" onClick={onClose}>×</button></header><div className="context-body">{tab==="object"&&activeFlow?.steps?.includes(object?.id)&&<button className="context-back" onClick={()=>{setTab("flows");}}>← К сценарию «{activeFlow.title}»</button>}<button className="copy-context" onClick={copyContext} title="Скопировать описание проекта и выбранного элемента, чтобы вставить в новый диалог с ИИ">Скопировать для диалога с ИИ</button>{pending&&["question","correction","probe","code-review"].includes(architect.kind)&&<p role="status">Обрабатываем запрос… Можно продолжать работать с картой.</p>}{architect?.status==="failed"&&["question","correction","probe"].includes(architect.kind)&&<p className="inline-error" role="alert">{jobMessage(architect)?.body}</p>}
    {architect?.status==="done"&&architect.kind==="probe"&&<p className="context-notice" role="status">Подключение к модели {architect.result?.model} подтверждено. Время: {jobStats.time} · Токены: {jobStats.tokens}.</p>}
    {tab==="overview"&&<><small>ПРОЕКТ</small><h2>{map.projectTitle||"Карта проекта"}</h2><p>{map.projectSummary||map.knowledge?.intent||"Описание проекта ещё не построено."}</p>{map.knowledge?.intent&&map.knowledge.intent!==map.projectSummary&&<p>{map.knowledge.intent}</p>}<dl>{details("Что проверено",map.verification?.state==="verified"?"Карта сверена с источниками":verificationLabels[map.verification?.state]||"Объём проверки не записан")}{details("Охват диалогов",map.knowledge?.coverage?`${map.knowledge.coverage.analyzed||0} сообщений разобрано; ${map.knowledge.coverage.pending||0} ожидают`:null)}</dl>{(map.knowledge?.unresolved||[]).length>0&&<details><summary>Что пока неясно</summary>{map.knowledge.unresolved.map((item,index)=><p key={index}>{typeof item==="string"?item:JSON.stringify(item)}</p>)}</details>}<form onSubmit={async event=>{event.preventDefault();try{setArchitect(await post("/api/questions",{question,checkpointId:snapshot._history?.id}));}catch(error){toast(error.message,true);}}}><label>Вопрос о проекте<textarea value={question} onChange={event=>setQuestion(event.target.value)} placeholder="Как проходит заявка? Что затронет изменение этого модуля?" required maxLength={3000}/></label><button disabled={pending}>Разобраться</button></form>{architect?.kind==="question"&&architect.result?.answer&&<div className="project-answer"><small className="muted-text" title={architect.result.checkpointId}>{architect.result.checkpointId==="live"?"Карта на момент вопроса":"Выбранное состояние истории"} · ревизия {architect.result.revision}</small><p>{architect.result.answer}</p>{evidence(architect.result.sourceIds)}</div>}</>}
    {tab==="object"&&object&&<><small>{kind==="route"?"СВЯЗЬ":kind==="work"?"РАБОТА":"ЭЛЕМЕНТ ПРОЕКТА"}</small><h2>{title(object)}</h2>{!historical&&!object.bundle&&["entity","area","route"].includes(kind)&&<div className="object-actions"><button onClick={()=>onRename(kind,object.id,title(object),object.ownerPurpose||object.ownerNote||object.purpose||object.note||"")}>Переименовать</button><button onClick={()=>document.getElementById("map-correction")?.scrollIntoView({block:"start"})}>Уточнить смысл</button></div>}<p>{object.ownerPurpose||object.ownerNote||object.purpose||object.note||object.summary}</p><dl>{details("Статус",statuses[object.status]||object.status)}{details("Почему",object.verification?.reason||object.statusReason||(object.status==="problem"?object.note:null))}{details("Замысел",statuses[object.intentStatus]||object.intentStatus)}{details("Реализация",statuses[object.implementationStatus]||object.implementationStatus)}{details("Получает",object.inputs)}{details("Передаёт",object.outputs)}{details("Достоверность описания",verificationLabels[object.verification?.state||map.verification?.state]||((object.evidence?.length||object.path)?"Источник указан; отдельная проверка не записана":"Источник не указан"))}</dl>{evidence([...(object.evidence||[]),object.path])}{(object.technicalName||object.acceptanceCriteria?.length>0)&&<details><summary>Технические подробности</summary><dl>{details("Имя в коде",object.technicalName)}{details("Условия работы",object.acceptanceCriteria)}</dl></details>}{object.bundle&&object.relations.map(relation=><button className="context-link" key={relation.id} onClick={()=>onRelation(relation.id)}><small>{title(entities.get(relation.from))} → {title(entities.get(relation.to))}</small><span>{relation.ownerLabel||relation.label}</span></button>)}{kind==="entity"&&<><h3>Связано с</h3>{snapshot.relations.filter(relation=>relation.from===object.id||relation.to===object.id).map(relation=><button className="context-link" key={relation.id} onClick={()=>onSelect(entities.get(relation.from===object.id?relation.to:relation.from))}><small>{relation.from===object.id?"→":"←"} {relation.ownerLabel||relation.label}</small><span>{title(entities.get(relation.from===object.id?relation.to:relation.from))}</span></button>)}</>}
      {!historical&&!object.bundle&&["entity","area","route"].includes(kind)&&<form className="correction-form" onSubmit={event=>{event.preventDefault();run({kind:kind==="route"?"relation":kind,id:object.id,action,instruction,otherId});}}><h3 id="map-correction">Поправить карту</h3><label>Что изменить<select value={action} onChange={event=>setAction(event.target.value)}><option value="explain">Уточнить или объяснить иначе</option>{["area","entity"].includes(kind)&&<option value="missing">Не хватает части</option>}{kind==="entity"&&<><option value="planned">Это пока план</option><option value="cancel">Замысел отменён</option><option value="group">Объединить в блок</option></>}{kind==="route"&&<option value="remove">Этой связи быть не должно</option>}</select></label>{action==="group"&&<label>Второй элемент<select value={otherId} onChange={event=>setOtherId(event.target.value)} required><option value="">Выбрать…</option>{snapshot.entities.filter(item=>item.id!==object.id&&item.areaId===object.areaId&&(item.parentId||"")===(object.parentId||"")).map(item=><option key={item.id} value={item.id}>{title(item)}</option>)}</select></label>}<div className="quick-corrections">{["Короче","Подробнее","Объясни через пример"].map(text=><button type="button" key={text} disabled={pending} onClick={()=>run({kind:kind==="route"?"relation":kind,id:object.id,action:"explain",instruction:text})}>{text}</button>)}</div><label>Своими словами<textarea value={instruction} onChange={event=>setInstruction(event.target.value)} placeholder={action==="group"?"Название общего блока":"Например: объясни без технических терминов"} maxLength={4000} required/></label><button disabled={pending}>Применить поправку</button></form>}
    </>}
    {tab==="flows"&&<>
      {!activeFlow?<><h2>Выберите сценарий</h2><p className="muted-text">Выбранный путь подсветится на карте. Каждый шаг можно открыть.</p>
        {!flows.length&&<p>Сценарии появятся после построения карты.</p>}
        {flows.map(flow=><section className="context-flow" key={flow.id}><button className="flow-title" onClick={()=>{setFlowId(flow.id);}}>{flow.title}<span aria-hidden="true"> →</span></button><p>{flow.trigger||flow.entry}</p></section>)}
      </>:<><button className="context-back" onClick={()=>setFlowId("")}>← Все сценарии</button><h2>{activeFlow.title}</h2><p>{activeFlow.trigger||activeFlow.entry}</p>
        {activeFlow.status==="unresolved"?<p>{activeFlow.unresolvedReason}</p>:<ol className="flow-steps">{(activeFlow.steps||[]).map((id,index)=><li key={id+"-"+index}><button onClick={()=>onSelect(entities.get(id))}>{title(entities.get(id))||id}</button>{activeFlow.transitions?.[index]&&<small>{activeFlow.transitions[index].condition||snapshot.relations.find(relation=>relation.id===activeFlow.transitions[index].relationId)?.label}</small>}</li>)}</ol>}
        {activeFlow.outcome&&<p><b>Результат:</b> {activeFlow.outcome}</p>}
        {!historical&&!activeFlow.legacy&&<details><summary>Уточнить сценарий</summary><form onSubmit={event=>{event.preventDefault();run({kind:"flow",id:activeFlow.id,instruction});}}><textarea aria-label="Поправка сценария" value={instruction} onChange={event=>setInstruction(event.target.value)} placeholder="Что объяснить иначе?" required/><button disabled={pending}>Применить поправку</button></form></details>}
      </>}
    </>}
    {tab==="decisions"&&<><h2>Почему устроено так</h2>{!(map.knowledge?.decisions||[]).length&&<p>В доступных диалогах пока нет сохранённых решений.</p>}{(map.knowledge?.decisions||[]).map(decision=><section className="context-decision" key={decision.id}><small>{statuses[decision.status]||decision.status} · {decision.at?new Date(decision.at).toLocaleDateString():""}</small><p>{decision.text}</p>{decision.reason&&<p className="muted-text">{decision.reason}</p>}{evidence(decision.sourceIds)}{!historical&&<details><summary>Уточнить решение</summary><form onSubmit={event=>{event.preventDefault();run({kind:"decision",id:decision.id,instruction});}}><textarea aria-label="Поправка решения" value={instruction} onChange={event=>setInstruction(event.target.value)} required/><button disabled={pending}>Применить поправку</button></form></details>}{!historical&&decision.status!=="cancelled"&&<button disabled={pending} onClick={()=>run({kind:"decision",id:decision.id,action:"cancel",instruction:"Владелец отменил это решение на карте"})}>Решение отменено</button>}</section>)}</>}
    {tab==="settings"&&<><h2>Язык карты</h2><p>{map.explanationProfile?.language||map.language||"Авто"} · {map.explanationProfile?.framing||"По вашим сообщениям в проекте"}</p><p>Пожелания меняют будущие пояснения. Исторические подписи сохраняются.</p><form onSubmit={event=>{event.preventDefault();run({kind:"profile",instruction});}}><label>Как вам понятнее<textarea value={instruction} onChange={event=>setInstruction(event.target.value)} placeholder="Говори о функциях продукта и их назначении. Термины объясняй бытовыми примерами." required/></label><button disabled={historical||pending}>Запомнить пожелание</button></form><h2>Исполнители</h2>{models?<form onSubmit={async event=>{event.preventDefault();try{await post("/api/models/config",{...limits,modelProvider:roleModels.architect.provider,enabled:observe,dialogSources:dialogs,modelPool:rolePool(roleModels)});toast("Настройки сохранены");loadModels();}catch(error){toast(error.message,true);}}}><ModelRoleFields models={models} value={roleModels} onChange={setRoleModels}/><ModelLimits value={limits} onChange={setLimits}/>{models.config.pausedByHost&&<p className="context-notice">Фоновые процессы временно приостановлены на этом запуске. <button type="button" onClick={async()=>{try{await post("/api/models/config",{modelProvider:roleModels.architect.provider,enabled:true,resumeObservation:true});toast("Наблюдение возобновлено");loadModels();}catch(error){toast(error.message,true);}}}>Возобновить наблюдение</button></p>}<label className="check-label"><input type="checkbox" checked={observe} onChange={event=>setObserve(event.target.checked)}/> Следить за кодом и работой агентов</label><label className="check-label"><input type="checkbox" checked={dialogs} onChange={event=>setDialogs(event.target.checked)}/> Читать диалоги этого проекта</label><div className="form-actions"><button disabled={pending}>Сохранить</button><button type="button" disabled={pending} onClick={async()=>{try{setArchitect(await post("/api/models/probe",{provider}));}catch(error){toast(error.message,true);}}}>Проверить подключение</button></div></form>:<p>Загружаем настройки…</p>}{sourceList&&<details><summary>Источники диалогов ({sourceList.records?.length||0})</summary>{(sourceList.records||[]).slice(-20).reverse().map(item=><button className="context-link" key={item.id} onClick={()=>showSource(item.id)}><small>{item.author} · {item.provider}</small><span>{item.preview}</span></button>)}</details>}</>}
    {correction&&!historical&&<div className="correction-result"><p>Поправка сохранена.</p><p>Время: {correction.jobStats?.time} · Токены: {correction.jobStats?.tokens} · Модель: {correction.jobStats?.models}</p><button onClick={async()=>{try{await post("/api/corrections/undo",{id:correction.id});setCorrection(null);refresh();toast("Поправка отменена");}catch(error){toast(error.message,true);}}}>Отменить поправку</button></div>}
    {tab==="health"&&<HealthPanel api={api}/>}
    {tab==="settings"&&reader()}
  </div></aside>;
}
