async(page)=>{
  const check=(value,message)=>{if(!value)throw new Error(message);};
  const state=()=>page.evaluate(async()=>(await fetch('/api/state')).json());
  const post=(path,body)=>page.evaluate(async({path,body})=>{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.error);return value;},{path,body});
  const waitState=async predicate=>{const until=Date.now()+20000;while(Date.now()<until){const value=await state();if(predicate(value))return value;await page.waitForTimeout(100);}throw new Error('Timed out waiting for recorded geometry');};
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.locator('.live-pill').click();
  await page.getByRole('button',{name:'Понять проект',exact:true}).click();
  await page.getByRole('heading',{name:'От заявки до результата'}).waitFor();
  await page.getByRole('button',{name:'Настройки',exact:true}).click();
  await page.getByRole('heading',{name:'Исполнители',exact:true}).waitFor();
  await page.getByRole('button',{name:'Закрыть контекст'}).click();
  await waitState(value=>Boolean(value._geometry));
  const first=await state();const before=await post('/api/history/checkpoint',{title:'До правки — приёмка'});
  await waitState(value=>value._historyHead?.id===before.id&&Boolean(value._geometry));
  const old=await state();const afterTitle='Приём заявки — после правки '+Date.now();
  await post('/api/rename',{canvasRevision:old.revision,kind:'entity',id:'module-0',values:{title:afterTitle,description:'Собирает данные клиента'}});
  await waitState(value=>value.entities.find(item=>item.id==='module-0').ownerLabel===afterTitle&&Boolean(value._geometry));
  const after=await state();const revision=after.revision;
  await page.waitForTimeout(850);
  await page.getByRole('button',{name:'Предыдущий чекпоинт',exact:true}).click();
  await page.waitForFunction(id=>document.querySelector('.app-shell')?.dataset.checkpoint===id,before.id);
  check(await page.getByRole('button',{name:'Обновить Canvas',exact:true}).isDisabled(),'Past permits rebuilding');
  check(await page.locator('.area-resize-control').count()===0,'Past permits resizing');
  const oldRevision=await page.locator('.app-shell').getAttribute('data-revision');
  check(Number(oldRevision)===old.revision,'Cursor shows the wrong revision');
  await page.getByRole('button',{name:'История ⌃',exact:true}).click();
  await page.getByRole('button',{name:'Сравнивать от выбранного',exact:true}).click();
  await page.getByRole('textbox',{name:'Комментарий к прошлому',exact:true}).fill('Историческое пояснение');
  await page.getByRole('button',{name:'Добавить',exact:true}).click();
  const liveMark=await post('/api/history/checkpoint',{title:'Пришло во время просмотра прошлого'});
  await page.waitForTimeout(1000);
  check(Number(await page.locator('.app-shell').getAttribute('data-revision'))===old.revision,'Live altered the selected past');
  await page.locator('.live-pill').click();
  await page.waitForFunction(revision=>Number(document.querySelector('.app-shell')?.dataset.revision)>revision,revision);
  await page.getByText('Добавлено 0 · изменено 1 · удалено 0',{exact:false}).waitFor();
  await page.getByRole('spinbutton',{name:'Шаг по чекпоинтам',exact:true}).fill('2');
  await page.getByRole('button',{name:'Предыдущий чекпоинт',exact:true}).click();
  await page.waitForFunction(id=>document.querySelector('.app-shell')?.dataset.checkpoint===id,before.id);
  await page.getByRole('spinbutton',{name:'Шаг по чекпоинтам',exact:true}).fill('1');
  const slider=page.getByRole('slider',{name:'Чекпоинт карты',exact:true});await slider.focus();await slider.press('ArrowRight');
  await page.waitForFunction(id=>document.querySelector('.app-shell')?.dataset.checkpoint===id,after._historyHead.id);
  const saved=await page.evaluate(async id=>(await fetch(`/api/history/state?id=${id}`)).json(),before.id);
  check(saved.entities.find(item=>item.id==='module-0').ownerLabel!==after.entities.find(item=>item.id==='module-0').ownerLabel,'Historical wording was overwritten');
  check(saved._geometry&&saved._history.geometry==='recorded','Historical geometry was not persisted');
  check((await state()).revision===liveMark.revision,'Seeking or commenting wrote graph events');
  await page.screenshot({path:'output/playwright/timeline-accepted.png'});
  await page.locator('.live-pill').click();
  await page.getByRole('button',{name:'История ⌄',exact:true}).click();
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'output/playwright/mobile-accepted.png'});
  check(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth),'Mobile page overflows');
  await page.setViewportSize({width:1440,height:900});
  check(!errors.length,errors.join('\n'));
  return {exactRevision:true,storedGeometry:true,immutableWording:true,manualSteps:[1,2],liveDuringPast:true,commentsDoNotAlterMap:true,responsive:true,errors};
}
